# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dev.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dev.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tdev.proto\"0\n\x1dPredictPostsForOneUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x94\x01\n\x1ePredictPostsForOneUserResponse\x12\x37\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32).PredictPostsForOneUserResponse.DataEntry\x1a\x39\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.StringArray:\x02\x38\x01\"\x1d\n\x0bStringArray\x12\x0e\n\x06values\x18\x01 \x03(\t2f\n\tRecSystem\x12Y\n\x16PredictPostsForOneUser\x12\x1e.PredictPostsForOneUserRequest\x1a\x1f.PredictPostsForOneUserResponseb\x06proto3')
)




_PREDICTPOSTSFORONEUSERREQUEST = _descriptor.Descriptor(
  name='PredictPostsForOneUserRequest',
  full_name='PredictPostsForOneUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='PredictPostsForOneUserRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=61,
)


_PREDICTPOSTSFORONEUSERRESPONSE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='PredictPostsForOneUserResponse.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PredictPostsForOneUserResponse.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PredictPostsForOneUserResponse.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=212,
)

_PREDICTPOSTSFORONEUSERRESPONSE = _descriptor.Descriptor(
  name='PredictPostsForOneUserResponse',
  full_name='PredictPostsForOneUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PredictPostsForOneUserResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PREDICTPOSTSFORONEUSERRESPONSE_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=212,
)


_STRINGARRAY = _descriptor.Descriptor(
  name='StringArray',
  full_name='StringArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='StringArray.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=243,
)

_PREDICTPOSTSFORONEUSERRESPONSE_DATAENTRY.fields_by_name['value'].message_type = _STRINGARRAY
_PREDICTPOSTSFORONEUSERRESPONSE_DATAENTRY.containing_type = _PREDICTPOSTSFORONEUSERRESPONSE
_PREDICTPOSTSFORONEUSERRESPONSE.fields_by_name['data'].message_type = _PREDICTPOSTSFORONEUSERRESPONSE_DATAENTRY
DESCRIPTOR.message_types_by_name['PredictPostsForOneUserRequest'] = _PREDICTPOSTSFORONEUSERREQUEST
DESCRIPTOR.message_types_by_name['PredictPostsForOneUserResponse'] = _PREDICTPOSTSFORONEUSERRESPONSE
DESCRIPTOR.message_types_by_name['StringArray'] = _STRINGARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictPostsForOneUserRequest = _reflection.GeneratedProtocolMessageType('PredictPostsForOneUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTPOSTSFORONEUSERREQUEST,
  __module__ = 'dev_pb2'
  # @@protoc_insertion_point(class_scope:PredictPostsForOneUserRequest)
  ))
_sym_db.RegisterMessage(PredictPostsForOneUserRequest)

PredictPostsForOneUserResponse = _reflection.GeneratedProtocolMessageType('PredictPostsForOneUserResponse', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _PREDICTPOSTSFORONEUSERRESPONSE_DATAENTRY,
    __module__ = 'dev_pb2'
    # @@protoc_insertion_point(class_scope:PredictPostsForOneUserResponse.DataEntry)
    ))
  ,
  DESCRIPTOR = _PREDICTPOSTSFORONEUSERRESPONSE,
  __module__ = 'dev_pb2'
  # @@protoc_insertion_point(class_scope:PredictPostsForOneUserResponse)
  ))
_sym_db.RegisterMessage(PredictPostsForOneUserResponse)
_sym_db.RegisterMessage(PredictPostsForOneUserResponse.DataEntry)

StringArray = _reflection.GeneratedProtocolMessageType('StringArray', (_message.Message,), dict(
  DESCRIPTOR = _STRINGARRAY,
  __module__ = 'dev_pb2'
  # @@protoc_insertion_point(class_scope:StringArray)
  ))
_sym_db.RegisterMessage(StringArray)


_PREDICTPOSTSFORONEUSERRESPONSE_DATAENTRY._options = None

_RECSYSTEM = _descriptor.ServiceDescriptor(
  name='RecSystem',
  full_name='RecSystem',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=245,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictPostsForOneUser',
    full_name='RecSystem.PredictPostsForOneUser',
    index=0,
    containing_service=None,
    input_type=_PREDICTPOSTSFORONEUSERREQUEST,
    output_type=_PREDICTPOSTSFORONEUSERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECSYSTEM)

DESCRIPTOR.services_by_name['RecSystem'] = _RECSYSTEM

# @@protoc_insertion_point(module_scope)
