# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dev.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dev.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tdev.proto\"A\n\x1dPredictPostsForOneUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x03(\t\"1\n\x1ePredictPostsForOneUserResponse\x12\x0f\n\x07post_id\x18\x01 \x03(\t2f\n\tRecSystem\x12Y\n\x16PredictPostsForOneUser\x12\x1e.PredictPostsForOneUserRequest\x1a\x1f.PredictPostsForOneUserResponseb\x06proto3')
)




_PREDICTPOSTSFORONEUSERREQUEST = _descriptor.Descriptor(
  name='PredictPostsForOneUserRequest',
  full_name='PredictPostsForOneUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='PredictPostsForOneUserRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_id', full_name='PredictPostsForOneUserRequest.post_id', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=78,
)


_PREDICTPOSTSFORONEUSERRESPONSE = _descriptor.Descriptor(
  name='PredictPostsForOneUserResponse',
  full_name='PredictPostsForOneUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='post_id', full_name='PredictPostsForOneUserResponse.post_id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['PredictPostsForOneUserRequest'] = _PREDICTPOSTSFORONEUSERREQUEST
DESCRIPTOR.message_types_by_name['PredictPostsForOneUserResponse'] = _PREDICTPOSTSFORONEUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PredictPostsForOneUserRequest = _reflection.GeneratedProtocolMessageType('PredictPostsForOneUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTPOSTSFORONEUSERREQUEST,
  __module__ = 'dev_pb2'
  # @@protoc_insertion_point(class_scope:PredictPostsForOneUserRequest)
  ))
_sym_db.RegisterMessage(PredictPostsForOneUserRequest)

PredictPostsForOneUserResponse = _reflection.GeneratedProtocolMessageType('PredictPostsForOneUserResponse', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTPOSTSFORONEUSERRESPONSE,
  __module__ = 'dev_pb2'
  # @@protoc_insertion_point(class_scope:PredictPostsForOneUserResponse)
  ))
_sym_db.RegisterMessage(PredictPostsForOneUserResponse)



_RECSYSTEM = _descriptor.ServiceDescriptor(
  name='RecSystem',
  full_name='RecSystem',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=131,
  serialized_end=233,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictPostsForOneUser',
    full_name='RecSystem.PredictPostsForOneUser',
    index=0,
    containing_service=None,
    input_type=_PREDICTPOSTSFORONEUSERREQUEST,
    output_type=_PREDICTPOSTSFORONEUSERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECSYSTEM)

DESCRIPTOR.services_by_name['RecSystem'] = _RECSYSTEM

# @@protoc_insertion_point(module_scope)
