# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dev_pb2 as dev__pb2


class RecSystemStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PredictPostsForOneUser = channel.unary_unary(
        '/RecSystem/PredictPostsForOneUser',
        request_serializer=dev__pb2.PredictPostsForOneUserRequest.SerializeToString,
        response_deserializer=dev__pb2.PredictPostsForOneUserResponse.FromString,
        )


class RecSystemServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PredictPostsForOneUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecSystemServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictPostsForOneUser': grpc.unary_unary_rpc_method_handler(
          servicer.PredictPostsForOneUser,
          request_deserializer=dev__pb2.PredictPostsForOneUserRequest.FromString,
          response_serializer=dev__pb2.PredictPostsForOneUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RecSystem', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
