server:
  AppVersion: 1.0.0
  Host: 0.0.0.0
  Port: 8000
  Mode: Development
  ReadTimeout: 60

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

jwt:
  SecretKey: secret
  SecretKeyExpire: 60
  RefreshKey: refresh
  RefreshKeyExpire: 60

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  DBName: api_db
  SSLMode: disable

aws:
  Endpoint: 127.0.0.1:9000
  MinioAccessKey: minio
  MinioSecretKey: minio123
  UseSSL: false
  MinioEndpoint: http://127.0.0.1:9000

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

grpcServices:
  WidgetsHost: localhost
  WidgetsPort: 50052
