version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - ./db/postgres:/data/postgres
      # - ./db/db.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    restart: unless-stopped

#  mongodb:
#    container_name: mongodb_container
#    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongo}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
#      MONGO_INITDB_DATABASE: mongodb
#    volumes:
#      - ./db/mongodb:/data/db
#      # - ./db/mongo-entrypoint:/docker-entrypoit-initdb.d
#    ports:
#      - "${MONGODB_PORT:-27017}:27017"
#    networks:
#      - mongodb

networks:
  postgres:
    driver: bridge
#  mongodb:
#    driver: bridge

volumes:
  postgres:
#  mongodb:
