import type { Metadata } from "next";
import Image from "next/image";
// шрифты

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NonRegLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <div className="absolute w-full h-full">
          <Image
            src="http://localhost:3000/reg-gray-linear.png"
            fill
            alt="reg-gray-linear"
          />
        </div>
        <main className="relative">{children}</main>
        <div className="absolute md:w-[110vw] w-[770px] md:h-[25vh] h-[15vh] bottom-0 left-[-10px]">
          <Image
            src="http://localhost:3000/reg-pink-linear.png"
            fill
            alt="reg-pink-linear"
          />
        </div>
      </body>
    </html>
  );
}
