// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: rec/rec.proto

package rec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RecSystem_PredictPostsForOneUser_FullMethodName  = "/RecSystem/PredictPostsForOneUser"
	RecSystem_ExecuteDataToFiles_FullMethodName      = "/RecSystem/ExecuteDataToFiles"
	RecSystem_GetAllModelNamesOfFiles_FullMethodName = "/RecSystem/GetAllModelNamesOfFiles"
	RecSystem_SetModel_FullMethodName                = "/RecSystem/SetModel"
	RecSystem_DeleteModelFromFiles_FullMethodName    = "/RecSystem/DeleteModelFromFiles"
	RecSystem_TrainModel_FullMethodName              = "/RecSystem/TrainModel"
	RecSystem_ValidateModel_FullMethodName           = "/RecSystem/ValidateModel"
)

// RecSystemClient is the client API for RecSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecSystemClient interface {
	PredictPostsForOneUser(ctx context.Context, in *PredictPostsForOneUserRequest, opts ...grpc.CallOption) (*PredictPostsForOneUserResponse, error)
	ExecuteDataToFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAllModelNamesOfFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllModelNamesOfFilesResponse, error)
	SetModel(ctx context.Context, in *SetModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteModelFromFiles(ctx context.Context, in *DeleteModelFromFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TrainModel(ctx context.Context, in *TrainModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ValidateModel(ctx context.Context, in *ValidateModelRequest, opts ...grpc.CallOption) (*ValidateModelResponse, error)
}

type recSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewRecSystemClient(cc grpc.ClientConnInterface) RecSystemClient {
	return &recSystemClient{cc}
}

func (c *recSystemClient) PredictPostsForOneUser(ctx context.Context, in *PredictPostsForOneUserRequest, opts ...grpc.CallOption) (*PredictPostsForOneUserResponse, error) {
	out := new(PredictPostsForOneUserResponse)
	err := c.cc.Invoke(ctx, RecSystem_PredictPostsForOneUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recSystemClient) ExecuteDataToFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecSystem_ExecuteDataToFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recSystemClient) GetAllModelNamesOfFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllModelNamesOfFilesResponse, error) {
	out := new(GetAllModelNamesOfFilesResponse)
	err := c.cc.Invoke(ctx, RecSystem_GetAllModelNamesOfFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recSystemClient) SetModel(ctx context.Context, in *SetModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecSystem_SetModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recSystemClient) DeleteModelFromFiles(ctx context.Context, in *DeleteModelFromFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecSystem_DeleteModelFromFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recSystemClient) TrainModel(ctx context.Context, in *TrainModelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RecSystem_TrainModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recSystemClient) ValidateModel(ctx context.Context, in *ValidateModelRequest, opts ...grpc.CallOption) (*ValidateModelResponse, error) {
	out := new(ValidateModelResponse)
	err := c.cc.Invoke(ctx, RecSystem_ValidateModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecSystemServer is the server API for RecSystem service.
// All implementations must embed UnimplementedRecSystemServer
// for forward compatibility
type RecSystemServer interface {
	PredictPostsForOneUser(context.Context, *PredictPostsForOneUserRequest) (*PredictPostsForOneUserResponse, error)
	ExecuteDataToFiles(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetAllModelNamesOfFiles(context.Context, *emptypb.Empty) (*GetAllModelNamesOfFilesResponse, error)
	SetModel(context.Context, *SetModelRequest) (*emptypb.Empty, error)
	DeleteModelFromFiles(context.Context, *DeleteModelFromFilesRequest) (*emptypb.Empty, error)
	TrainModel(context.Context, *TrainModelRequest) (*emptypb.Empty, error)
	ValidateModel(context.Context, *ValidateModelRequest) (*ValidateModelResponse, error)
	mustEmbedUnimplementedRecSystemServer()
}

// UnimplementedRecSystemServer must be embedded to have forward compatible implementations.
type UnimplementedRecSystemServer struct {
}

func (UnimplementedRecSystemServer) PredictPostsForOneUser(context.Context, *PredictPostsForOneUserRequest) (*PredictPostsForOneUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictPostsForOneUser not implemented")
}
func (UnimplementedRecSystemServer) ExecuteDataToFiles(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDataToFiles not implemented")
}
func (UnimplementedRecSystemServer) GetAllModelNamesOfFiles(context.Context, *emptypb.Empty) (*GetAllModelNamesOfFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllModelNamesOfFiles not implemented")
}
func (UnimplementedRecSystemServer) SetModel(context.Context, *SetModelRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetModel not implemented")
}
func (UnimplementedRecSystemServer) DeleteModelFromFiles(context.Context, *DeleteModelFromFilesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModelFromFiles not implemented")
}
func (UnimplementedRecSystemServer) TrainModel(context.Context, *TrainModelRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrainModel not implemented")
}
func (UnimplementedRecSystemServer) ValidateModel(context.Context, *ValidateModelRequest) (*ValidateModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateModel not implemented")
}
func (UnimplementedRecSystemServer) mustEmbedUnimplementedRecSystemServer() {}

// UnsafeRecSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecSystemServer will
// result in compilation errors.
type UnsafeRecSystemServer interface {
	mustEmbedUnimplementedRecSystemServer()
}

func RegisterRecSystemServer(s grpc.ServiceRegistrar, srv RecSystemServer) {
	s.RegisterService(&RecSystem_ServiceDesc, srv)
}

func _RecSystem_PredictPostsForOneUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictPostsForOneUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecSystemServer).PredictPostsForOneUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecSystem_PredictPostsForOneUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecSystemServer).PredictPostsForOneUser(ctx, req.(*PredictPostsForOneUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecSystem_ExecuteDataToFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecSystemServer).ExecuteDataToFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecSystem_ExecuteDataToFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecSystemServer).ExecuteDataToFiles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecSystem_GetAllModelNamesOfFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecSystemServer).GetAllModelNamesOfFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecSystem_GetAllModelNamesOfFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecSystemServer).GetAllModelNamesOfFiles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecSystem_SetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecSystemServer).SetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecSystem_SetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecSystemServer).SetModel(ctx, req.(*SetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecSystem_DeleteModelFromFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelFromFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecSystemServer).DeleteModelFromFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecSystem_DeleteModelFromFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecSystemServer).DeleteModelFromFiles(ctx, req.(*DeleteModelFromFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecSystem_TrainModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecSystemServer).TrainModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecSystem_TrainModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecSystemServer).TrainModel(ctx, req.(*TrainModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecSystem_ValidateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecSystemServer).ValidateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecSystem_ValidateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecSystemServer).ValidateModel(ctx, req.(*ValidateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecSystem_ServiceDesc is the grpc.ServiceDesc for RecSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RecSystem",
	HandlerType: (*RecSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PredictPostsForOneUser",
			Handler:    _RecSystem_PredictPostsForOneUser_Handler,
		},
		{
			MethodName: "ExecuteDataToFiles",
			Handler:    _RecSystem_ExecuteDataToFiles_Handler,
		},
		{
			MethodName: "GetAllModelNamesOfFiles",
			Handler:    _RecSystem_GetAllModelNamesOfFiles_Handler,
		},
		{
			MethodName: "SetModel",
			Handler:    _RecSystem_SetModel_Handler,
		},
		{
			MethodName: "DeleteModelFromFiles",
			Handler:    _RecSystem_DeleteModelFromFiles_Handler,
		},
		{
			MethodName: "TrainModel",
			Handler:    _RecSystem_TrainModel_Handler,
		},
		{
			MethodName: "ValidateModel",
			Handler:    _RecSystem_ValidateModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rec/rec.proto",
}
