// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v4.25.3
// source: widgets/widgets.proto

package rec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiniUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Login     string `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Avatar    string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *MiniUserInfo) Reset() {
	*x = MiniUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiniUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniUserInfo) ProtoMessage() {}

func (x *MiniUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniUserInfo.ProtoReflect.Descriptor instead.
func (*MiniUserInfo) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{0}
}

func (x *MiniUserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MiniUserInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MiniUserInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MiniUserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *MiniUserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetMostLikedUserInfoByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserId string `protobuf:"bytes,1,opt,name=currentUserId,proto3" json:"currentUserId,omitempty"`
}

func (x *GetMostLikedUserInfoByUserIdRequest) Reset() {
	*x = GetMostLikedUserInfoByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMostLikedUserInfoByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostLikedUserInfoByUserIdRequest) ProtoMessage() {}

func (x *GetMostLikedUserInfoByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostLikedUserInfoByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetMostLikedUserInfoByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{1}
}

func (x *GetMostLikedUserInfoByUserIdRequest) GetCurrentUserId() string {
	if x != nil {
		return x.CurrentUserId
	}
	return ""
}

type GetMostLikedUserInfoByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *MiniUserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
}

func (x *GetMostLikedUserInfoByUserIdResponse) Reset() {
	*x = GetMostLikedUserInfoByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMostLikedUserInfoByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostLikedUserInfoByUserIdResponse) ProtoMessage() {}

func (x *GetMostLikedUserInfoByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostLikedUserInfoByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetMostLikedUserInfoByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{2}
}

func (x *GetMostLikedUserInfoByUserIdResponse) GetUserInfo() *MiniUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type TagInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Count int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{3}
}

func (x *TagInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TagInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetMostLikedTagByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserId string `protobuf:"bytes,1,opt,name=currentUserId,proto3" json:"currentUserId,omitempty"`
}

func (x *GetMostLikedTagByUserIdRequest) Reset() {
	*x = GetMostLikedTagByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMostLikedTagByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostLikedTagByUserIdRequest) ProtoMessage() {}

func (x *GetMostLikedTagByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostLikedTagByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetMostLikedTagByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{4}
}

func (x *GetMostLikedTagByUserIdRequest) GetCurrentUserId() string {
	if x != nil {
		return x.CurrentUserId
	}
	return ""
}

type GetMostLikedTagByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagInfo *TagInfo `protobuf:"bytes,1,opt,name=tagInfo,proto3" json:"tagInfo,omitempty"`
}

func (x *GetMostLikedTagByUserIdResponse) Reset() {
	*x = GetMostLikedTagByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMostLikedTagByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostLikedTagByUserIdResponse) ProtoMessage() {}

func (x *GetMostLikedTagByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostLikedTagByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetMostLikedTagByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{5}
}

func (x *GetMostLikedTagByUserIdResponse) GetTagInfo() *TagInfo {
	if x != nil {
		return x.TagInfo
	}
	return nil
}

type GetMostViewedUserInfoByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentUserId string `protobuf:"bytes,1,opt,name=currentUserId,proto3" json:"currentUserId,omitempty"`
}

func (x *GetMostViewedUserInfoByUserIdRequest) Reset() {
	*x = GetMostViewedUserInfoByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMostViewedUserInfoByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostViewedUserInfoByUserIdRequest) ProtoMessage() {}

func (x *GetMostViewedUserInfoByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostViewedUserInfoByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetMostViewedUserInfoByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{6}
}

func (x *GetMostViewedUserInfoByUserIdRequest) GetCurrentUserId() string {
	if x != nil {
		return x.CurrentUserId
	}
	return ""
}

type GetMostViewedUserInfoByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *MiniUserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
}

func (x *GetMostViewedUserInfoByUserIdResponse) Reset() {
	*x = GetMostViewedUserInfoByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widgets_widgets_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMostViewedUserInfoByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostViewedUserInfoByUserIdResponse) ProtoMessage() {}

func (x *GetMostViewedUserInfoByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostViewedUserInfoByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetMostViewedUserInfoByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{7}
}

func (x *GetMostViewedUserInfoByUserIdResponse) GetUserInfo() *MiniUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_widgets_widgets_proto protoreflect.FileDescriptor

var file_widgets_widgets_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2f, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73,
	0x22, 0x86, 0x01, 0x0a, 0x0c, 0x4d, 0x69, 0x6e, 0x69, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x4b, 0x0a, 0x23, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x24, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x45, 0x0a, 0x07, 0x54, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54, 0x61, 0x67, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x4d, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64,
	0x54, 0x61, 0x67, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x54,
	0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x74, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x4c, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5a, 0x0a,
	0x25, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xfb, 0x02, 0x0a, 0x0e, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x1c,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x2e, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x4c, 0x69,
	0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54, 0x61, 0x67, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x54, 0x61, 0x67, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x64, 0x54, 0x61, 0x67, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7e, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x73, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x73, 0x63, 0x68, 0x2f, 0x63, 0x6f,
	0x6f, 0x6c, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_widgets_widgets_proto_rawDescOnce sync.Once
	file_widgets_widgets_proto_rawDescData = file_widgets_widgets_proto_rawDesc
)

func file_widgets_widgets_proto_rawDescGZIP() []byte {
	file_widgets_widgets_proto_rawDescOnce.Do(func() {
		file_widgets_widgets_proto_rawDescData = protoimpl.X.CompressGZIP(file_widgets_widgets_proto_rawDescData)
	})
	return file_widgets_widgets_proto_rawDescData
}

var file_widgets_widgets_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_widgets_widgets_proto_goTypes = []interface{}{
	(*MiniUserInfo)(nil),                          // 0: widgets.MiniUserInfo
	(*GetMostLikedUserInfoByUserIdRequest)(nil),   // 1: widgets.GetMostLikedUserInfoByUserIdRequest
	(*GetMostLikedUserInfoByUserIdResponse)(nil),  // 2: widgets.GetMostLikedUserInfoByUserIdResponse
	(*TagInfo)(nil),                               // 3: widgets.TagInfo
	(*GetMostLikedTagByUserIdRequest)(nil),        // 4: widgets.GetMostLikedTagByUserIdRequest
	(*GetMostLikedTagByUserIdResponse)(nil),       // 5: widgets.GetMostLikedTagByUserIdResponse
	(*GetMostViewedUserInfoByUserIdRequest)(nil),  // 6: widgets.GetMostViewedUserInfoByUserIdRequest
	(*GetMostViewedUserInfoByUserIdResponse)(nil), // 7: widgets.GetMostViewedUserInfoByUserIdResponse
}
var file_widgets_widgets_proto_depIdxs = []int32{
	0, // 0: widgets.GetMostLikedUserInfoByUserIdResponse.userInfo:type_name -> widgets.MiniUserInfo
	3, // 1: widgets.GetMostLikedTagByUserIdResponse.tagInfo:type_name -> widgets.TagInfo
	0, // 2: widgets.GetMostViewedUserInfoByUserIdResponse.userInfo:type_name -> widgets.MiniUserInfo
	1, // 3: widgets.WidgetsService.GetMostLikedUserInfoByUserId:input_type -> widgets.GetMostLikedUserInfoByUserIdRequest
	4, // 4: widgets.WidgetsService.GetMostLikedTagByUserId:input_type -> widgets.GetMostLikedTagByUserIdRequest
	6, // 5: widgets.WidgetsService.GetMostViewedUserInfoByUserId:input_type -> widgets.GetMostViewedUserInfoByUserIdRequest
	2, // 6: widgets.WidgetsService.GetMostLikedUserInfoByUserId:output_type -> widgets.GetMostLikedUserInfoByUserIdResponse
	5, // 7: widgets.WidgetsService.GetMostLikedTagByUserId:output_type -> widgets.GetMostLikedTagByUserIdResponse
	7, // 8: widgets.WidgetsService.GetMostViewedUserInfoByUserId:output_type -> widgets.GetMostViewedUserInfoByUserIdResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_widgets_widgets_proto_init() }
func file_widgets_widgets_proto_init() {
	if File_widgets_widgets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_widgets_widgets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiniUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widgets_widgets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMostLikedUserInfoByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widgets_widgets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMostLikedUserInfoByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widgets_widgets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widgets_widgets_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMostLikedTagByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widgets_widgets_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMostLikedTagByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widgets_widgets_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMostViewedUserInfoByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widgets_widgets_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMostViewedUserInfoByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_widgets_widgets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_widgets_widgets_proto_goTypes,
		DependencyIndexes: file_widgets_widgets_proto_depIdxs,
		MessageInfos:      file_widgets_widgets_proto_msgTypes,
	}.Build()
	File_widgets_widgets_proto = out.File
	file_widgets_widgets_proto_rawDesc = nil
	file_widgets_widgets_proto_goTypes = nil
	file_widgets_widgets_proto_depIdxs = nil
}
