// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: widgets/widgets.proto

package rec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WidgetsService_GetMostLikedUserInfoByUserId_FullMethodName  = "/widgets.WidgetsService/GetMostLikedUserInfoByUserId"
	WidgetsService_GetMostLikedTagByUserId_FullMethodName       = "/widgets.WidgetsService/GetMostLikedTagByUserId"
	WidgetsService_GetMostViewedUserInfoByUserId_FullMethodName = "/widgets.WidgetsService/GetMostViewedUserInfoByUserId"
)

// WidgetsServiceClient is the client API for WidgetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WidgetsServiceClient interface {
	GetMostLikedUserInfoByUserId(ctx context.Context, in *GetMostLikedUserInfoByUserIdRequest, opts ...grpc.CallOption) (*GetMostLikedUserInfoByUserIdResponse, error)
	GetMostLikedTagByUserId(ctx context.Context, in *GetMostLikedTagByUserIdRequest, opts ...grpc.CallOption) (*GetMostLikedTagByUserIdResponse, error)
	GetMostViewedUserInfoByUserId(ctx context.Context, in *GetMostViewedUserInfoByUserIdRequest, opts ...grpc.CallOption) (*GetMostViewedUserInfoByUserIdResponse, error)
}

type widgetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWidgetsServiceClient(cc grpc.ClientConnInterface) WidgetsServiceClient {
	return &widgetsServiceClient{cc}
}

func (c *widgetsServiceClient) GetMostLikedUserInfoByUserId(ctx context.Context, in *GetMostLikedUserInfoByUserIdRequest, opts ...grpc.CallOption) (*GetMostLikedUserInfoByUserIdResponse, error) {
	out := new(GetMostLikedUserInfoByUserIdResponse)
	err := c.cc.Invoke(ctx, WidgetsService_GetMostLikedUserInfoByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetsServiceClient) GetMostLikedTagByUserId(ctx context.Context, in *GetMostLikedTagByUserIdRequest, opts ...grpc.CallOption) (*GetMostLikedTagByUserIdResponse, error) {
	out := new(GetMostLikedTagByUserIdResponse)
	err := c.cc.Invoke(ctx, WidgetsService_GetMostLikedTagByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetsServiceClient) GetMostViewedUserInfoByUserId(ctx context.Context, in *GetMostViewedUserInfoByUserIdRequest, opts ...grpc.CallOption) (*GetMostViewedUserInfoByUserIdResponse, error) {
	out := new(GetMostViewedUserInfoByUserIdResponse)
	err := c.cc.Invoke(ctx, WidgetsService_GetMostViewedUserInfoByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WidgetsServiceServer is the server API for WidgetsService service.
// All implementations must embed UnimplementedWidgetsServiceServer
// for forward compatibility
type WidgetsServiceServer interface {
	GetMostLikedUserInfoByUserId(context.Context, *GetMostLikedUserInfoByUserIdRequest) (*GetMostLikedUserInfoByUserIdResponse, error)
	GetMostLikedTagByUserId(context.Context, *GetMostLikedTagByUserIdRequest) (*GetMostLikedTagByUserIdResponse, error)
	GetMostViewedUserInfoByUserId(context.Context, *GetMostViewedUserInfoByUserIdRequest) (*GetMostViewedUserInfoByUserIdResponse, error)
	mustEmbedUnimplementedWidgetsServiceServer()
}

// UnimplementedWidgetsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWidgetsServiceServer struct {
}

func (UnimplementedWidgetsServiceServer) GetMostLikedUserInfoByUserId(context.Context, *GetMostLikedUserInfoByUserIdRequest) (*GetMostLikedUserInfoByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostLikedUserInfoByUserId not implemented")
}
func (UnimplementedWidgetsServiceServer) GetMostLikedTagByUserId(context.Context, *GetMostLikedTagByUserIdRequest) (*GetMostLikedTagByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostLikedTagByUserId not implemented")
}
func (UnimplementedWidgetsServiceServer) GetMostViewedUserInfoByUserId(context.Context, *GetMostViewedUserInfoByUserIdRequest) (*GetMostViewedUserInfoByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostViewedUserInfoByUserId not implemented")
}
func (UnimplementedWidgetsServiceServer) mustEmbedUnimplementedWidgetsServiceServer() {}

// UnsafeWidgetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WidgetsServiceServer will
// result in compilation errors.
type UnsafeWidgetsServiceServer interface {
	mustEmbedUnimplementedWidgetsServiceServer()
}

func RegisterWidgetsServiceServer(s grpc.ServiceRegistrar, srv WidgetsServiceServer) {
	s.RegisterService(&WidgetsService_ServiceDesc, srv)
}

func _WidgetsService_GetMostLikedUserInfoByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostLikedUserInfoByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServiceServer).GetMostLikedUserInfoByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetsService_GetMostLikedUserInfoByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServiceServer).GetMostLikedUserInfoByUserId(ctx, req.(*GetMostLikedUserInfoByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetsService_GetMostLikedTagByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostLikedTagByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServiceServer).GetMostLikedTagByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetsService_GetMostLikedTagByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServiceServer).GetMostLikedTagByUserId(ctx, req.(*GetMostLikedTagByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetsService_GetMostViewedUserInfoByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostViewedUserInfoByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServiceServer).GetMostViewedUserInfoByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetsService_GetMostViewedUserInfoByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServiceServer).GetMostViewedUserInfoByUserId(ctx, req.(*GetMostViewedUserInfoByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WidgetsService_ServiceDesc is the grpc.ServiceDesc for WidgetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WidgetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "widgets.WidgetsService",
	HandlerType: (*WidgetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMostLikedUserInfoByUserId",
			Handler:    _WidgetsService_GetMostLikedUserInfoByUserId_Handler,
		},
		{
			MethodName: "GetMostLikedTagByUserId",
			Handler:    _WidgetsService_GetMostLikedTagByUserId_Handler,
		},
		{
			MethodName: "GetMostViewedUserInfoByUserId",
			Handler:    _WidgetsService_GetMostViewedUserInfoByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "widgets/widgets.proto",
}
