import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Noto_Sans } from "next/font/google";
import { Providers } from "@/components/providers/providers";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
// Иконки
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from "@/components/nav-bar/nav-bar";
config.autoAddCss = false;

// шрифты
const notoSans = Noto_Sans({
  subsets: ["latin", "cyrillic"],
  variable: "--noto-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <Providers>
          <body className={` ${notoSans.className}`}>{children}</body>
        </Providers>
      </NextIntlClientProvider>
    </html>
  );
}
