POST http://localhost:8000/api/v1/user/sign/up HTTP/1.1
Content-Type: application/json

{
  "phone": "+79234567891",
  "login": "someloginheh",
  "password": "somepas123",
  "name": "Name",
  "surname": "Surname",
  "dateOfBirth": "01-11-2023",
  "gender": "Male",
  "userRole": "user"
}

###
GET http://localhost:8000/api/v1/user/phone/+79234567891 HTTP/1.1

###
GET http://localhost:8000/api/v1/user/login/someloginheh HTTP/1.1

###
POST http://localhost:8000/api/v1/user/sign/in/phone HTTP/1.1
Content-Type: application/json

{
  "phone": "+79234567891",
  "password": "somepas123"
}

###
POST http://localhost:8000/api/v1/user/sign/in/login HTTP/1.1
Content-Type: application/json

{
  "login": "someloginheh",
  "password": "somepas123"
}

###
POST http://localhost:8000/api/v1/user/sign/out
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzIjoxNzAxMzcyNTgzLCJpZCI6IjZkODc1MmQ5LTc3MzQtNGNjNy1hNDA3LTE5ZDI4OWI5YWExNSJ9.z7ZxS8G70PzIAPmtLiYcgd-E1mRD7EMGl4iNXrPeBNA

###
POST http://localhost:8000/api/v1/comment/4c5c9a7e-8068-4767-b8b5-b2ddf3102597/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzIjoxNzAxNDIzODc3LCJpZCI6IjZkODc1MmQ5LTc3MzQtNGNjNy1hNDA3LTE5ZDI4OWI5YWExNSJ9.EeBsDoZ7lo6vGaWW7fgBVPM25a14Nyna0HIvMqkauAg

###
POST http://localhost:8000/api/v1/comment/4c5c9a7e-8068-4767-b8b5-b2ddf3102597/unlike
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzIjoxNzAxNDIzODc3LCJpZCI6IjZkODc1MmQ5LTc3MzQtNGNjNy1hNDA3LTE5ZDI4OWI5YWExNSJ9.EeBsDoZ7lo6vGaWW7fgBVPM25a14Nyna0HIvMqkauAg
